-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- TRIVIA TABLE (Public content)
create table public.trivia (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null, -- The main trivia text
  explanation text, -- Detailed explanation
  source_url text,
  category text,
  published_date date unique, -- One main trivia per day, or use this to schedule
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TRIVIA CANDIDATES (For Admin Workflow)
create table public.trivia_candidates (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  explanation text,
  source_url text,
  category text,
  status text default 'pending', -- pending, approved, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PROFILES (User data)
create table public.profiles (
  id uuid references auth.users not null primary key,
  is_subscribed boolean default false,
  subscription_tier text default 'free',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- USER SAVES (Bookmarks)
create table public.user_saves (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  trivia_id bigint references public.trivia(id) on delete cascade not null,
  folder_name text default 'default',
  saved_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, trivia_id)
);

-- DAILY READS (To tracking daily limit)
create table public.daily_reads (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  read_date date default current_date not null,
  count int default 0,
  unique(user_id, read_date)
);

-- RLS POLICIES (Basic)
alter table public.trivia enable row level security;
create policy "Public trivia is viewable by everyone" on public.trivia for select using (true);

alter table public.profiles enable row level security;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

alter table public.user_saves enable row level security;
create policy "Users can manage own saves" on public.user_saves for all using (auth.uid() = user_id);

alter table public.daily_reads enable row level security;
create policy "Users can manage own reads" on public.daily_reads for all using (auth.uid() = user_id);
